apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: faker
kind: ConfigMap
metadata:
  name: example-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
    component: nginx
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
    component: flask-server
  name: flask-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app
      component: flask-server
  template:
    metadata:
      labels:
        app: flask-app
        component: flask-server
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-config
        image: cremerfc/flask-app:131
        name: flask-app
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
