apiVersion: v1
data:
  PAGE_MESSAGE: '{{ repl ConfigOption "page-message-input"}}'
kind: ConfigMap
metadata:
  name: appdirect-config-map
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
    component: nginx
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-direct
    component: app-server
  name: app-direct-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-direct
      component: app-server
  template:
    metadata:
      labels:
        app: app-direct
        component: app-server
    spec:
      containers:
      - env:
        - name: PAGE_MESSAGE
          valueFrom:
            configMapKeyRef:
              key: PAGE_MESSAGE
              name: appdirect-config-map
        image: cremerfc/appdirect:latest
        name: appdirect
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: example-nginx
          servicePort: 80
        path: /
