apiVersion: v1
data:
  PAGE_MESSAGE: Hello!
kind: ConfigMap
metadata:
  name: appdirect-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: app-direct-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: app-direct
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-direct
    component: app-server
  name: app-direct-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-direct
      component: app-server
  template:
    metadata:
      labels:
        app: app-direct
        component: app-server
    spec:
      containers:
      - env:
        - name: PAGE_MESSAGE
          valueFrom:
            configMapKeyRef:
              key: PAGE_MESSAGE
              name: appdirect-config-map
        image: cremerfc/appdirect:latest
        name: appdirect
        ports:
        - containerPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: app-direct-service
          servicePort: 80
        path: /
